'use client'
import { useEffect, useState } from 'react'
import { Badge, Card, PageHeader, StatCard, money } from '@/components/finora-ui'

type Client={id:string;name:string;type:string}
type Proposal={id:string;proposalNumber:string;status:string;totalAmount:any;validUntil:string;client:Client;items:any[];invoice?:any}
type Invoice={id:string;invoiceNumber:string;status:string;totalAmount:any;dueDate:string;client:Client;payments:any[]}
type Payment={id:string;amount:any;paymentDate:string;method:string;invoice:any}
type Expense={id:string;category:string;amount:any;expenseDate:string;status:string;vendor:Client}
type Budget={id:string;category:string;period:string;plannedAmount:any}

export function ProposalsManager({role}:{role:string}){
 const [rows,setRows]=useState<Proposal[]>([]),[clients,setClients]=useState<Client[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[q,setQ]=useState(''),[message,setMessage]=useState('')
 const [form,setForm]=useState({clientId:'',validUntil:'',description:'',qty:1,unitPrice:0})
 async function load(){const [a,b]=await Promise.all([fetch('/api/proposals'),fetch('/api/clients?type=CLIENT')]);setRows((await a.json()).proposals||[]);setClients((await b.json()).clients||[])}
 useEffect(()=>{load()},[])
 async function save(e:any){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/proposals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:form.clientId,validUntil:form.validUntil||new Date(Date.now()+14*864e5).toISOString().slice(0,10),items:[{description:form.description||'Jasa profesional',qty:form.qty,unitPrice:form.unitPrice}],})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage('Proposal berhasil dibuat.');setOpen(false);await load()}catch(e){setMessage(e instanceof Error?e.message:'Gagal menyimpan.')}finally{setBusy(false)}}
 async function convert(id:string){setBusy(true);try{const r=await fetch(`/api/proposals/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'CONVERT'})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(`Invoice ${d.invoice.invoiceNumber} berhasil dibuat.`);await load()}catch(e){setMessage(e instanceof Error?e.message:'Gagal konversi.')}finally{setBusy(false)}}
 const filtered=rows.filter(x=>`${x.proposalNumber} ${x.client.name}`.toLowerCase().includes(q.toLowerCase()))
 return <div className="f-content"><PageHeader eyebrow="Penjualan / Proposal" title="Proposal" description="Buat, kirim, dan konversi penawaran menjadi invoice." action={['OWNER','FINANCE','SALES'].includes(role)&&<button className="f-btn primary" onClick={()=>setOpen(true)}>＋ Buat Proposal</button>}/>
  <div className="f-grid-3"><StatCard label="Total proposal" value={rows.length} icon="▤"/><StatCard label="Diterima" value={rows.filter(x=>x.status==='ACCEPTED').length} icon="✓"/><StatCard label="Nilai proposal" value={money(rows.reduce((s,x)=>s+Number(x.totalAmount),0))} icon="Rp"/></div><div style={{height:16}}/>
  <Card><div className="f-toolbar"><input className="f-input" placeholder="Cari nomor atau klien..." value={q} onChange={e=>setQ(e.target.value)}/>{message&&<span className="f-badge green">{message}</span>}</div><div style={{overflowX:'auto'}}><table className="f-table"><thead><tr><th>Proposal</th><th>Klien</th><th>Valid sampai</th><th>Nilai</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><strong>{x.proposalNumber}</strong></td><td>{x.client.name}</td><td>{new Date(x.validUntil).toLocaleDateString('id-ID')}</td><td className="f-number">{money(Number(x.totalAmount))}</td><td><Badge tone={x.status==='ACCEPTED'?'green':x.status==='REJECTED'?'red':'blue'}>{x.status}</Badge></td><td>{x.invoice?<a className="f-btn soft" href="/invoices">Lihat invoice</a>:<button className="f-btn soft" disabled={busy} onClick={()=>convert(x.id)}>Convert ke invoice</button>}</td></tr>)}</tbody></table></div></Card>
  {open&&<Modal title="Buat Proposal" onClose={()=>setOpen(false)}><form className="f-form" onSubmit={save}><label>Klien<select className="f-select" required value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">Pilih klien</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Berlaku sampai<input className="f-input" type="date" value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})}/></label><label>Deskripsi<textarea className="f-textarea" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="f-form-grid"><label>Qty<input className="f-input" type="number" min="1" value={form.qty} onChange={e=>setForm({...form,qty:Number(e.target.value)})}/></label><label>Harga satuan<input className="f-input" type="number" min="0" value={form.unitPrice} onChange={e=>setForm({...form,unitPrice:Number(e.target.value)})}/></label></div><button className="f-btn primary" disabled={busy}>{busy?'Menyimpan...':'Simpan proposal'}</button></form></Modal>}
 </div>
}

export function InvoicesManager({role}:{role:string}){
 const [rows,setRows]=useState<Invoice[]>([]),[clients,setClients]=useState<Client[]>([]),[open,setOpen]=useState(false),[payId,setPayId]=useState<string|null>(null),[msg,setMsg]=useState('')
 const [form,setForm]=useState({clientId:'',dueDate:'',description:'Jasa profesional',qty:1,unitPrice:0})
 async function load(){const [a,b]=await Promise.all([fetch('/api/invoices'),fetch('/api/clients?type=CLIENT')]);setRows((await a.json()).invoices||[]);setClients((await b.json()).clients||[])}
 useEffect(()=>{load()},[])
 async function save(e:any){e.preventDefault();const r=await fetch('/api/invoices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:form.clientId,dueDate:form.dueDate||new Date(Date.now()+14*864e5).toISOString().slice(0,10),items:[{description:form.description,qty:form.qty,unitPrice:form.unitPrice}]})});const d=await r.json();setMsg(r.ok?'Invoice berhasil dibuat.':d.error);if(r.ok){setOpen(false);load()}}
 return <div className="f-content"><PageHeader eyebrow="Penjualan / Tagihan" title="Invoice" description="Kelola tagihan, jatuh tempo, dan status pembayaran." action={['OWNER','FINANCE','SALES'].includes(role)&&<button className="f-btn primary" onClick={()=>setOpen(true)}>＋ Buat Invoice</button>}/><div className="f-grid-4"><StatCard label="Total invoice" value={rows.length} icon="▧"/><StatCard label="Belum dibayar" value={rows.filter(x=>x.status!=='PAID').length} icon="◷"/><StatCard label="Nilai piutang" value={money(rows.filter(x=>x.status!=='PAID').reduce((s,x)=>s+Number(x.totalAmount),0))} icon="Rp"/><StatCard label="Lunas" value={rows.filter(x=>x.status==='PAID').length} icon="✓"/></div><div style={{height:16}}/><Card><div className="f-card-head"><div><h3>Daftar invoice</h3><p>Invoice yang terkait dengan client workspace ini.</p></div>{msg&&<span className="f-badge green">{msg}</span>}</div><div style={{overflowX:'auto'}}><table className="f-table"><thead><tr><th>Invoice</th><th>Klien</th><th>Jatuh tempo</th><th>Total</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.invoiceNumber}</strong></td><td>{x.client.name}</td><td>{new Date(x.dueDate).toLocaleDateString('id-ID')}</td><td className="f-number">{money(Number(x.totalAmount))}</td><td><Badge tone={x.status==='PAID'?'green':x.status==='OVERDUE'?'red':'amber'}>{x.status}</Badge></td><td>{x.status!=='PAID'&&<button className="f-btn soft" onClick={()=>setPayId(x.id)}>Catat pembayaran</button>}</td></tr>)}</tbody></table></div></Card>
 {open&&<Modal title="Buat Invoice" onClose={()=>setOpen(false)}><form className="f-form" onSubmit={save}><label>Klien<select className="f-select" required value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">Pilih klien</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Jatuh tempo<input className="f-input" type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label>Deskripsi<textarea className="f-textarea" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="f-form-grid"><label>Qty<input className="f-input" type="number" min="1" value={form.qty} onChange={e=>setForm({...form,qty:Number(e.target.value)})}/></label><label>Harga satuan<input className="f-input" type="number" value={form.unitPrice} onChange={e=>setForm({...form,unitPrice:Number(e.target.value)})}/></label></div><button className="f-btn primary">Simpan invoice</button></form></Modal>}
 {payId&&<PaymentModal invoice={rows.find(x=>x.id===payId)!} onClose={()=>setPayId(null)} onSaved={()=>{setPayId(null);load()}}/>}
 </div>
}

function PaymentModal({invoice,onClose,onSaved}:{invoice:Invoice;onClose:()=>void;onSaved:()=>void}){
 const [amount,setAmount]=useState(String(Number(invoice.totalAmount)));const [method,setMethod]=useState('BANK_TRANSFER');const [busy,setBusy]=useState(false);const [err,setErr]=useState('')
 async function submit(e:any){e.preventDefault();setBusy(true);const r=await fetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({invoiceId:invoice.id,amount:Number(amount),paymentDate:new Date().toISOString().slice(0,10),method})});const d=await r.json();if(!r.ok)setErr(d.error);else onSaved();setBusy(false)}
 return <Modal title={`Pembayaran ${invoice.invoiceNumber}`} onClose={onClose}><form className="f-form" onSubmit={submit}><div className="f-card pad"><span className="f-muted">Total invoice</span><div className="f-number" style={{fontSize:22}}>{money(Number(invoice.totalAmount))}</div></div><label>Nominal<input className="f-input" type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Metode<select className="f-select" value={method} onChange={e=>setMethod(e.target.value)}><option value="BANK_TRANSFER">Transfer Bank</option><option value="CASH">Cash</option><option value="PAYMENT_GATEWAY">Payment Gateway</option></select></label>{err&&<span className="f-badge red">{err}</span>}<button className="f-btn primary" disabled={busy}>{busy?'Menyimpan...':'Simpan pembayaran'}</button></form></Modal>
}

export function PaymentsManager({role}:{role:string}){const [rows,setRows]=useState<Payment[]>([]);useEffect(()=>{fetch('/api/payments').then(r=>r.json()).then(d=>setRows(d.payments||[]))},[]);return <div className="f-content"><PageHeader eyebrow="Kas / Payment" title="Pembayaran" description="Riwayat uang masuk yang berasal dari invoice."/><Card><div style={{overflowX:'auto'}}><table className="f-table"><thead><tr><th>Tanggal</th><th>Invoice</th><th>Klien</th><th>Metode</th><th>Nominal</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{new Date(x.paymentDate).toLocaleDateString('id-ID')}</td><td>{x.invoice.invoiceNumber}</td><td>{x.invoice.client.name}</td><td>{x.method}</td><td className="f-number">{money(Number(x.amount))}</td><td><Badge tone="green">Selesai</Badge></td></tr>)}</tbody></table></div>{!rows.length&&<div className="f-empty"><strong>Belum ada pembayaran</strong>Pembayaran akan muncul setelah Anda mencatat payment pada invoice.</div>}</Card></div>}

export function ExpensesManager({role}:{role:string}){
 const [rows,setRows]=useState<Expense[]>([]),[vendors,setVendors]=useState<Client[]>([]),[open,setOpen]=useState(false),[msg,setMsg]=useState('')
 const [form,setForm]=useState({vendorId:'',category:'Operasional',amount:0,expenseDate:new Date().toISOString().slice(0,10)})
 async function load(){const [a,b]=await Promise.all([fetch('/api/expenses'),fetch('/api/clients?type=VENDOR')]);setRows((await a.json()).expenses||[]);setVendors((await b.json()).clients||[])}useEffect(()=>{load()},[])
 async function save(e:any){e.preventDefault();const r=await fetch('/api/expenses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();setMsg(r.ok?'Biaya berhasil dicatat.':d.error);if(r.ok){setOpen(false);load()}}
 async function approve(id:string){const r=await fetch(`/api/expenses/${id}/approve`,{method:'POST'});if(r.ok)load();else{const d=await r.json();setMsg(d.error)}}
 return <div className="f-content"><PageHeader eyebrow="Operasional" title="Biaya (Expense)" description="Catat pengeluaran dan proses approval berdasarkan threshold." action={['OWNER','FINANCE','SALES'].includes(role)&&<button className="f-btn primary" onClick={()=>setOpen(true)}>＋ Tambah Biaya</button>}/><div className="f-grid-3"><StatCard label="Total tercatat" value={money(rows.reduce((s,x)=>s+Number(x.amount),0))} icon="◈"/><StatCard label="Menunggu approval" value={rows.filter(x=>x.status==='PENDING').length} icon="!"/><StatCard label="Disetujui" value={rows.filter(x=>x.status==='APPROVED').length} icon="✓"/></div><div style={{height:16}}/><Card><div className="f-card-head">{msg&&<span className="f-badge green">{msg}</span>}</div><div style={{overflowX:'auto'}}><table className="f-table"><thead><tr><th>Tanggal</th><th>Kategori</th><th>Vendor</th><th>Nominal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{new Date(x.expenseDate).toLocaleDateString('id-ID')}</td><td>{x.category}</td><td>{x.vendor.name}</td><td className="f-number">{money(Number(x.amount))}</td><td><Badge tone={x.status==='APPROVED'?'green':'amber'}>{x.status}</Badge></td><td>{x.status==='PENDING'&&['OWNER','FINANCE'].includes(role)&&<button className="f-btn soft" onClick={()=>approve(x.id)}>Approve</button>}</td></tr>)}</tbody></table></div></Card>{open&&<Modal title="Catat Biaya" onClose={()=>setOpen(false)}><form className="f-form" onSubmit={save}><label>Vendor<select className="f-select" required value={form.vendorId} onChange={e=>setForm({...form,vendorId:e.target.value})}><option value="">Pilih vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Kategori<input className="f-input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Nominal<input className="f-input" type="number" min="1" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></label><label>Tanggal<input className="f-input" type="date" value={form.expenseDate} onChange={e=>setForm({...form,expenseDate:e.target.value})}/></label><button className="f-btn primary">Simpan biaya</button></form></Modal>}</div>
}

export function BudgetsManager({role}:{role:string}){
 const [rows,setRows]=useState<Budget[]>([]),[open,setOpen]=useState(false);const [form,setForm]=useState({category:'Operasional',period:new Date().getFullYear().toString(),plannedAmount:0})
 async function load(){const r=await fetch('/api/budgets');const d=await r.json();setRows(d.budgets||[])}useEffect(()=>{load()},[])
 async function save(e:any){e.preventDefault();const r=await fetch('/api/budgets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(r.ok){setOpen(false);load()}}
 return <div className="f-content"><PageHeader eyebrow="Kontrol" title="Anggaran (Budget)" description="Tetapkan rencana anggaran dan pantau penyerapan per kategori." action={['OWNER','FINANCE'].includes(role)&&<button className="f-btn primary" onClick={()=>setOpen(true)}>＋ Buat Anggaran</button>}/><div className="f-grid-3">{rows.slice(0,3).map((x,i)=><StatCard key={x.id} label={x.category} value={money(Number(x.plannedAmount))} icon={['◎','◈','▦'][i%3]}/>)}</div><div style={{height:16}}/><Card><div style={{overflowX:'auto'}}><table className="f-table"><thead><tr><th>Kategori</th><th>Periode</th><th>Rencana</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.category}</strong></td><td>{x.period}</td><td className="f-number">{money(Number(x.plannedAmount))}</td><td><Badge tone="green">Aktif</Badge></td></tr>)}</tbody></table></div>{!rows.length&&<div className="f-empty"><strong>Belum ada anggaran</strong>Buat anggaran pertama untuk mengontrol pengeluaran.</div>}</Card>{open&&<Modal title="Buat Anggaran" onClose={()=>setOpen(false)}><form className="f-form" onSubmit={save}><label>Kategori<input className="f-input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Periode<input className="f-input" value={form.period} onChange={e=>setForm({...form,period:e.target.value})}/></label><label>Nominal rencana<input className="f-input" type="number" min="1" value={form.plannedAmount} onChange={e=>setForm({...form,plannedAmount:Number(e.target.value)})}/></label><button className="f-btn primary">Simpan anggaran</button></form></Modal>}</div>
}

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div style={{position:'fixed',inset:0,background:'rgba(3,30,27,.42)',display:'grid',placeItems:'center',zIndex:100,padding:16}}><div className="f-card" style={{width:'min(520px,100%)',maxHeight:'90vh',overflow:'auto'}}><div className="f-card-head"><h3>{title}</h3><button className="f-btn" onClick={onClose}>Tutup</button></div>{children}</div></div>}
