'use client'
import { useEffect, useState } from 'react'

export default function ProjectDocumentsManager({projectId, role}:{projectId:string;role:string}){
  const [docs,setDocs]=useState<any[]>([]);const [file,setFile]=useState<File|null>(null);const [title,setTitle]=useState('');const [category,setCategory]=useState('GENERAL');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  const canWrite=['OWNER','FINANCE'].includes(role)
  async function load(){const r=await fetch(`/api/project-documents?projectId=${projectId}`);const d=await r.json();setDocs(d.documents||[])}
  useEffect(()=>{load()},[projectId])
  async function upload(){if(!file||!title)return;setBusy(true);setError('');try{const form=new FormData();form.append('projectId',projectId);form.append('title',title);form.append('category',category);form.append('file',file);const r=await fetch('/api/project-documents',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw new Error(d.error||'Upload gagal.');setTitle('');setFile(null);await load()}catch(e){setError(e instanceof Error?e.message:'Upload gagal.')}finally{setBusy(false)}}
  async function remove(id:string){if(!confirm('Hapus dokumen ini?'))return;const r=await fetch(`/api/project-documents/${id}`,{method:'DELETE'});if(!r.ok){const d=await r.json();setError(d.error||'Gagal menghapus.');return}load()}
  return <section className="f-card" id="documents-project"><div className="f-card-head"><div><h3>Project Documents</h3><p>Dokumen kontrak, PO, progress, berita acara, dan bukti pendukung dalam satu tempat.</p></div><span className="f-badge neutral">{docs.length} file</span></div>{error&&<div className="f-inline-alert error">{error}</div>}{canWrite&&<div className="f-form-grid" style={{padding:16}}><label>Judul<input className="f-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="BAST, kontrak, foto progress…"/></label><label>Kategori<select className="f-select" value={category} onChange={e=>setCategory(e.target.value)}><option>GENERAL</option><option>CONTRACT</option><option>PO</option><option>PROGRESS</option><option>DELIVERY</option><option>INVOICE</option><option>PAYMENT</option><option>OTHER</option></select></label><label>File<input className="f-input" type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div style={{alignSelf:'end'}}><button className="f-btn primary" disabled={busy||!file||!title} onClick={upload}>{busy?'Mengunggah…':'Upload'}</button></div></div>}{docs.length===0?<div className="f-empty">Belum ada dokumen project.</div>:<div className="f-list">{docs.map(d=><div key={d.id} className="f-list-item"><div><strong>{d.title}</strong><small className="f-muted" style={{display:'block'}}>{d.category} · {d.fileName} · {Math.max(1,Math.round(d.sizeBytes/1024))} KB</small></div><div style={{display:'flex',gap:6}}><a className="f-btn soft" href={`/api/project-documents/${d.id}`}>Download</a>{canWrite&&<button className="f-btn soft" onClick={()=>remove(d.id)}>Hapus</button>}</div></div>)}</div>}</section>
}
