import { NextResponse } from 'next/server'
import { prisma } from '@/lib/db/prisma'
import { getCurrentFinoraContext, canManageFinance } from '@/lib/auth/current-user'
import { requireText } from '@/lib/validation/finance'
import { writeAuditLog } from '@/lib/audit'

export const dynamic='force-dynamic'
export async function GET(){const c=await getCurrentFinoraContext();if(!c)return NextResponse.json({error:'Unauthenticated'},{status:401});const rows=await prisma.accountingPeriod.findMany({where:{workspaceId:c.workspace.id},orderBy:{period:'desc'}});return NextResponse.json({periods:rows})}
export async function POST(req:Request){const c=await getCurrentFinoraContext();if(!c)return NextResponse.json({error:'Unauthenticated'},{status:401});if(c.user.role!=='OWNER')return NextResponse.json({error:'Hanya Owner yang dapat menutup/membuka periode.'},{status:403});try{const b=await req.json();const period=requireText(b.period,'Periode',7);if(!/^\d{4}-\d{2}$/.test(period))throw new Error('Periode harus YYYY-MM.');const action=String(b.action||'OPEN').toUpperCase();const row=await prisma.accountingPeriod.upsert({where:{workspaceId_period:{workspaceId:c.workspace.id,period}},create:{workspaceId:c.workspace.id,period,status:'OPEN'},update:{}});if(action==='CLOSE'){if(row.status==='CLOSED')return NextResponse.json({period:row});const accounts=await prisma.bankAccount.findMany({where:{workspaceId:c.workspace.id,isActive:true},select:{id:true}});if(accounts.length){const start=new Date(`${period}-01T00:00:00.000Z`);const end=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0));const reconCount=await prisma.bankReconciliation.count({where:{workspaceId:c.workspace.id,periodStart:start,periodEnd:end,status:'RECONCILED',bankAccountId:{in:accounts.map(a=>a.id)}}});if(reconCount!==accounts.length)return NextResponse.json({error:'Semua rekening bank aktif harus direkonsiliasi sebelum periode ditutup.'},{status:409})}const u=await prisma.accountingPeriod.update({where:{id:row.id},data:{status:'CLOSED',closedAt:new Date(),closedByUserId:c.user.id}});await writeAuditLog({workspaceId:c.workspace.id,actorUserId:c.user.id,action:'CLOSE',entityType:'ACCOUNTING_PERIOD',entityId:u.id,metadata:{period}});return NextResponse.json({period:u})}if(action==='REOPEN'){const reason=requireText(b.reason,'Alasan reopen',1000);const u=await prisma.accountingPeriod.update({where:{id:row.id},data:{status:'OPEN',reopenedAt:new Date(),reopenedByUserId:c.user.id,reopenReason:reason}});await writeAuditLog({workspaceId:c.workspace.id,actorUserId:c.user.id,action:'REOPEN',entityType:'ACCOUNTING_PERIOD',entityId:u.id,metadata:{period,reason}});return NextResponse.json({period:u})}return NextResponse.json({error:'Action harus CLOSE atau REOPEN.'},{status:400})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Gagal mengubah periode.'},{status:400})}}
