import { NextResponse } from 'next/server'
import { prisma } from '@/lib/db/prisma'
import { getCurrentFinoraContext, canManageFinance } from '@/lib/auth/current-user'
import { dateOnly, positiveMoney, requireText, parseMoneyCents, centsToDecimal } from '@/lib/validation/finance'
import { writeAuditLog } from '@/lib/audit'
import { assertAccountingPeriodOpen } from '@/lib/finance-period'
export const dynamic='force-dynamic'
export async function GET(){const c=await getCurrentFinoraContext();if(!c)return NextResponse.json({error:'Unauthenticated'},{status:401});const rows=await prisma.creditNote.findMany({where:{workspaceId:c.workspace.id},include:{invoice:{select:{id:true,invoiceNumber:true,totalAmount:true,status:true}},issuedBy:{select:{id:true,name:true}},voidedBy:{select:{id:true,name:true}}},orderBy:{issueDate:'desc'}});return NextResponse.json({creditNotes:rows})}
export async function POST(req:Request){const c=await getCurrentFinoraContext();if(!c)return NextResponse.json({error:'Unauthenticated'},{status:401});if(!canManageFinance(c.user.role))return NextResponse.json({error:'Tidak memiliki akses.'},{status:403});try{const b=await req.json();const invoiceId=requireText(b.invoiceId,'Invoice');const invoice=await prisma.invoice.findFirst({where:{id:invoiceId,client:{workspaceId:c.workspace.id}},include:{payments:true,creditNotes:{where:{status:'ISSUED'}}}});if(!invoice)return NextResponse.json({error:'Invoice tidak ditemukan.'},{status:404});if(['CANCELLED','VOID'].includes(invoice.status))return NextResponse.json({error:'Invoice tidak dapat diberi credit note.'},{status:409});const total=positiveMoney(b.totalAmount,'Nilai credit note').cents;const already=invoice.creditNotes.reduce((s,x)=>s+parseMoneyCents(x.totalAmount.toString()),0n);const paid=invoice.payments.reduce((s,x)=>s+parseMoneyCents(x.amount.toString()),0n);const max=paid>0n ? parseMoneyCents(invoice.totalAmount.toString())-already-paid : parseMoneyCents(invoice.totalAmount.toString())-already;if(total<=0n||total>max) return NextResponse.json({error:'Nilai credit note melebihi nilai invoice yang masih dapat dikoreksi.'},{status:409});const issueDate=dateOnly(b.issueDate,'Tanggal');await assertAccountingPeriodOpen(c.workspace.id,issueDate);const number=requireText(b.number,'Nomor credit note',80);const subtotalCents = b.subtotalAmount !== undefined ? positiveMoney(b.subtotalAmount, 'Subtotal credit note').cents : total
const taxCents = b.taxAmount !== undefined ? positiveMoney(b.taxAmount, 'Pajak credit note').cents : 0n
if (subtotalCents + taxCents !== total) throw new Error('Total credit note harus sama dengan subtotal + pajak.')
const subtotalAmount = centsToDecimal(subtotalCents)
const taxAmount = centsToDecimal(taxCents)
const existingNumber = await prisma.creditNote.findFirst({ where: { workspaceId: c.workspace.id, number } })
if (existingNumber) return NextResponse.json({ error: 'Nomor credit note sudah digunakan di workspace ini.' }, { status: 409 })
const row=await prisma.creditNote.create({data:{workspaceId:c.workspace.id,invoiceId,number,status:'DRAFT',issueDate,reason:requireText(b.reason,'Alasan',2000),subtotalAmount,taxAmount,totalAmount:centsToDecimal(total),notes:b.notes?String(b.notes):null}});await writeAuditLog({workspaceId:c.workspace.id,actorUserId:c.user.id,action:'CREATE',entityType:'CREDIT_NOTE',entityId:row.id,metadata:{number,total:row.totalAmount.toString()}});return NextResponse.json({creditNote:row},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Gagal membuat credit note.'},{status:400})}}
