import { NextResponse } from 'next/server'
import { prisma } from '@/lib/db/prisma'
import { getCurrentFinoraContext, canManageFinance } from '@/lib/auth/current-user'
import { dateOnly, positiveMoney, requireText, parseMoneyCents } from '@/lib/validation/finance'
import { writeAuditLog } from '@/lib/audit'
import { assertAccountingPeriodOpen } from '@/lib/finance-period'
export const dynamic='force-dynamic'
export async function GET(){const c=await getCurrentFinoraContext();if(!c)return NextResponse.json({error:'Unauthenticated'},{status:401});const rows=await prisma.payrollRun.findMany({where:{workspaceId:c.workspace.id},include:{lines:{include:{employee:true,allocations:true}}},orderBy:{period:'desc'}});return NextResponse.json({payrollRuns:rows})}
export async function POST(req:Request){const c=await getCurrentFinoraContext();if(!c)return NextResponse.json({error:'Unauthenticated'},{status:401});if(!canManageFinance(c.user.role))return NextResponse.json({error:'Tidak memiliki akses.'},{status:403});try{const b=await req.json();const period=requireText(b.period,'Periode',7);if(!/^\d{4}-\d{2}$/.test(period))throw new Error('Periode payroll harus YYYY-MM.');const payDate=dateOnly(b.payDate,'Tanggal payroll');await assertAccountingPeriodOpen(c.workspace.id,payDate);const lines=Array.isArray(b.lines)?b.lines:[];if(!lines.length)throw new Error('Minimal satu karyawan.');type PayrollAllocationInput = { projectId: string; percentage: string | number; amount: string | number };
    type PayrollLineInput = { employeeId: string; grossAmount: string | number; pph21Amount?: string | number; bpjsAmount?: string | number; otherDeduction?: string | number; taxableAmount?: string | number; allocations?: PayrollAllocationInput[] };
    const lineData = (lines as PayrollLineInput[]).map((x: PayrollLineInput) =>{const gross=positiveMoney(x.grossAmount,'Gross').cents;const pph=Number(x.pph21Amount??0)>0?positiveMoney(x.pph21Amount,'PPh21').cents:0n;const bpjs=Number(x.bpjsAmount??0)>0?positiveMoney(x.bpjsAmount,'BPJS').cents:0n;const other=Number(x.otherDeduction??0)>0?positiveMoney(x.otherDeduction,'Potongan lain').cents:0n;const net=gross-pph-bpjs-other;if(net<0n)throw new Error('Net payroll tidak boleh negatif.');return {employeeId:String(x.employeeId),grossAmount:gross,taxableAmount: x.taxableAmount!==undefined?positiveMoney(x.taxableAmount,'Taxable').cents:gross,pph21Amount:pph,bpjsAmount:bpjs,otherDeduction:other,netAmount:net,allocations:Array.isArray(x.allocations)?x.allocations:[]}});const gross = lineData.reduce((sum: bigint, x: { grossAmount: bigint }) => sum + x.grossAmount, 0n);const deductions = lineData.reduce((sum: bigint, x: { pph21Amount: bigint; bpjsAmount: bigint; otherDeduction: bigint }) => sum + x.pph21Amount + x.bpjsAmount + x.otherDeduction, 0n);const net = lineData.reduce((sum: bigint, x: { netAmount: bigint }) => sum + x.netAmount, 0n);const row=await prisma.$transaction(async tx=>tx.payrollRun.create({data:{workspaceId:c.workspace.id,runNumber:requireText(b.runNumber,'Nomor payroll',80),period,status:'DRAFT',payDate,grossAmount:gross.toString(),deductionAmount:deductions.toString(),netAmount:net.toString(),lines:{create:lineData.map(x=>({employeeId:x.employeeId,grossAmount:x.grossAmount.toString(),taxableAmount:x.taxableAmount.toString(),pph21Amount:x.pph21Amount.toString(),bpjsAmount:x.bpjsAmount.toString(),otherDeduction:x.otherDeduction.toString(),netAmount:x.netAmount.toString(),allocations:{create:x.allocations.map((a: PayrollAllocationInput)=>({projectId:String(a.projectId),percentage:String(a.percentage),amount:String(a.amount)}))}}))}},include:{lines:true}}));await writeAuditLog({workspaceId:c.workspace.id,actorUserId:c.user.id,action:'CREATE',entityType:'PAYROLL_RUN',entityId:row.id,metadata:{period,gross:gross.toString(),net:net.toString()}});return NextResponse.json({payrollRun:row},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Gagal membuat payroll.'},{status:400})}}
