'use client'
import { useMemo, useState } from 'react'
type Client={id:string;name:string;type:string;email:string|null;phone:string|null;picName:string|null;address:string|null;npwp:string|null;isActive:boolean}
type Props={initialClients:Client[];workspace:{id:string;name:string};role:string}
const empty={name:'',type:'CLIENT',email:'',phone:'',picName:'',address:'',npwp:'',isActive:true}
const canManage=(r:string)=>['OWNER','FINANCE','SALES'].includes(r)
const canDelete=(r:string)=>['OWNER','FINANCE'].includes(r)
export default function ClientVendorManager({initialClients,workspace,role}:Props){
 const [rows,setRows]=useState(initialClients),[q,setQ]=useState(''),[type,setType]=useState('ALL'),[archived,setArchived]=useState(false),[form,setForm]=useState<any>(empty),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState('')
 const filtered=useMemo(()=>rows.filter(x=>(type==='ALL'||x.type===type)&&(archived||x.isActive)&&(!q||`${x.name} ${x.email||''} ${x.picName||''} ${x.phone||''}`.toLowerCase().includes(q.toLowerCase()))),[rows,q,type,archived])
 const stats={clients:rows.filter(x=>x.type==='CLIENT'&&x.isActive).length,vendors:rows.filter(x=>x.type==='VENDOR'&&x.isActive).length,inactive:rows.filter(x=>!x.isActive).length}
 function edit(x?:Client){setForm(x?{...x}: {...empty});setOpen(true);setNotice('')}
 async function save(e:any){e.preventDefault();setSaving(true);setNotice('');try{const editing=Boolean(form.id);const r=await fetch(editing?`/api/clients/${form.id}`:'/api/clients',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error);setRows(cur=>editing?cur.map(x=>x.id===d.client.id?d.client:x):[...cur,d.client].sort((a,b)=>a.name.localeCompare(b.name)));setOpen(false);setNotice(editing?'Kontak diperbarui.':'Kontak ditambahkan.')}catch(e){setNotice(e instanceof Error?e.message:'Gagal menyimpan.')}finally{setSaving(false)}}
 async function archive(x:Client){if(!canDelete(role))return;if(!confirm(`${x.name} akan dinonaktifkan. Lanjutkan?`))return;const r=await fetch(`/api/clients/${x.id}`,{method:'DELETE'});const d=await r.json();if(r.ok){setRows(cur=>d.action==='deleted'?cur.filter(z=>z.id!==x.id):cur.map(z=>z.id===x.id?d.client:z));setNotice(d.action==='deleted'?'Kontak dihapus.':'Kontak diarsipkan.')}else setNotice(d.error||'Gagal.')}
 return <div className="f-content">
  <div className="f-pagehead"><div><div className="f-eyebrow">Master Data</div><h1>Klien & Vendor</h1><p>Kelola satu sumber data kontak untuk proposal, invoice, biaya, dan histori transaksi.</p></div>{canManage(role)&&<button className="f-btn primary" onClick={()=>edit()}>＋ Tambah Kontak</button>}</div>
  <div className="f-grid-3" style={{marginBottom:16}}><Stat label="Klien Aktif" value={stats.clients} icon="♙"/><Stat label="Vendor Aktif" value={stats.vendors} icon="▣"/><Stat label="Diarsipkan" value={stats.inactive} icon="□"/></div>
  <div className="f-panel-grid">
   <section className="f-card"><div className="f-card-head"><div><h3>Semua kontak</h3><p>{filtered.length} kontak ditampilkan</p></div><div className="f-badge neutral">Workspace: {workspace.name}</div></div>
    <div className="f-toolbar"><input className="f-input" placeholder="Cari nama, email, PIC..." value={q} onChange={e=>setQ(e.target.value)}/><select className="f-select" value={type} onChange={e=>setType(e.target.value)}><option value="ALL">Semua tipe</option><option value="CLIENT">Klien</option><option value="VENDOR">Vendor</option></select><label className="f-badge neutral" style={{gap:6}}><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Arsip</label></div>
    {notice&&<div style={{padding:'0 16px 12px'}}><span className="f-badge green">{notice}</span></div>}
    <div style={{overflowX:'auto'}}><table className="f-table"><thead><tr><th>Nama / Perusahaan</th><th>Tipe</th><th>Kontak</th><th>Status</th><th>Dibuat</th><th>Aksi</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><strong>{x.name}</strong><div className="f-muted" style={{fontSize:10}}>{x.picName||'PIC belum diisi'}</div></td><td><span className={`f-badge ${x.type==='CLIENT'?'blue':'amber'}`}>{x.type==='CLIENT'?'Klien':'Vendor'}</span></td><td><div>{x.email||'—'}</div><div className="f-muted" style={{fontSize:10}}>{x.phone||'—'}</div></td><td><span className={`f-badge ${x.isActive?'green':'neutral'}`}>{x.isActive?'Aktif':'Diarsipkan'}</span></td><td>{x.id? 'Tersimpan':'—'}</td><td><div style={{display:'flex',gap:6}}>{canManage(role)&&<button className="f-btn" onClick={()=>edit(x)}>Edit</button>}{canDelete(role)&&x.isActive&&<button className="f-btn" onClick={()=>archive(x)}>Arsip</button>}</div></td></tr>)}</tbody></table></div>
    {!filtered.length&&<div className="f-empty"><strong>Belum ada kontak</strong>Gunakan tombol Tambah Kontak untuk membuat master data pertama.</div>}
   </section>
   <section className="f-card"><div className="f-card-head"><div><h3>Tambah kontak</h3><p>Form cepat untuk master data baru.</p></div></div><form className="f-form" onSubmit={save}><label>Tipe<select className="f-select" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="CLIENT">Klien</option><option value="VENDOR">Vendor</option></select></label><label>Nama perusahaan *<input className="f-input" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="PT Nama Perusahaan"/></label><label>PIC<input className="f-input" value={form.picName} onChange={e=>setForm({...form,picName:e.target.value})} placeholder="Nama PIC"/></label><label>Email *<input className="f-input" required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="finance@perusahaan.id"/></label><label>Telepon<input className="f-input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+62 ..."/></label><label>Alamat<textarea className="f-textarea" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>NPWP<input className="f-input" value={form.npwp} onChange={e=>setForm({...form,npwp:e.target.value})}/></label><div style={{display:'flex',gap:8}}><button type="button" className="f-btn" onClick={()=>setForm(empty)}>Reset</button>{canManage(role)&&<button className="f-btn primary" disabled={saving}>{saving?'Menyimpan...':'Simpan Kontak'}</button>}</div></form></section>
  </div>
  {open&&<div style={{position:'fixed',inset:0,zIndex:100,background:'rgba(0,39,35,.38)',display:'grid',placeItems:'center',padding:16}}><div className="f-card" style={{width:'min(600px,100%)'}}><div className="f-card-head"><div><h3>{form.id?'Edit Kontak':'Tambah Kontak'}</h3><p>Perubahan akan tersimpan ke Neon.</p></div><button className="f-btn" onClick={()=>setOpen(false)}>Tutup</button></div><form className="f-form" onSubmit={save}><div className="f-form-grid"><label>Nama perusahaan *<input className="f-input" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Tipe<select className="f-select" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="CLIENT">Klien</option><option value="VENDOR">Vendor</option></select></label><label>PIC<input className="f-input" value={form.picName} onChange={e=>setForm({...form,picName:e.target.value})}/></label><label>Email *<input className="f-input" required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Telepon<input className="f-input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>NPWP<input className="f-input" value={form.npwp} onChange={e=>setForm({...form,npwp:e.target.value})}/></label><label className="full">Alamat<textarea className="f-textarea" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></div><button className="f-btn primary" disabled={saving}>{saving?'Menyimpan...':'Simpan perubahan'}</button></form></div></div>}
 </div>
}
function Stat({label,value,icon}:{label:string;value:number;icon:string}){return <div className="f-stat"><div className="f-stat-icon">{icon}</div><div className="f-stat-body"><span>{label}</span><strong>{value}</strong><small>Data workspace aktif</small></div></div>}
