import { NextResponse } from 'next/server'
import { prisma } from '@/lib/db/prisma'
import { writeAuditLog } from '@/lib/audit'
import { getCurrentFinoraContext } from '@/lib/auth/current-user'
import { dateOnly, positiveMoney, requireText } from '@/lib/validation/finance'

async function owned(id:string,workspaceId:string){return prisma.cashflowTransaction.findFirst({where:{id,workspaceId}})}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){
 const c=await getCurrentFinoraContext();if(!c)return NextResponse.json({error:'Unauthenticated'},{status:401});if(!['OWNER','FINANCE'].includes(c.user.role))return NextResponse.json({error:'Hanya Owner/Finance.'},{status:403});const {id}=await params;const existing=await owned(id,c.workspace.id);if(!existing)return NextResponse.json({error:'Transaksi kas tidak ditemukan.'},{status:404});if(existing.paymentId||existing.expenseId)return NextResponse.json({error:'Transaksi otomatis dari payment/expense tidak dapat diedit manual.'},{status:409});try{const b=await req.json();const type=String(b.type||'').toUpperCase();if(!['INCOME','EXPENSE'].includes(type))throw new Error('Tipe transaksi harus INCOME atau EXPENSE.');const category=requireText(b.category,'Kategori',120);const amount=positiveMoney(b.amount,'Nominal');const transactionDate=dateOnly(b.transactionDate,'Tanggal transaksi');const sourceRef=String(b.sourceRef??'').trim()||null;const row=await prisma.cashflowTransaction.update({where:{id},data:{type,category,amount:amount.decimal,transactionDate,sourceRef}});await writeAuditLog({workspaceId:c.workspace.id,actorUserId:c.user.id,action:'UPDATE',entityType:'CASHFLOW_TRANSACTION',entityId:id,metadata:{type,category}});return NextResponse.json({transaction:row})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Gagal memperbarui transaksi.'},{status:400})}}
export async function DELETE(_req:Request,{params}:{params:Promise<{id:string}>}){const c=await getCurrentFinoraContext();if(!c)return NextResponse.json({error:'Unauthenticated'},{status:401});if(!['OWNER','FINANCE'].includes(c.user.role))return NextResponse.json({error:'Hanya Owner/Finance.'},{status:403});const {id}=await params;const existing=await owned(id,c.workspace.id);if(!existing)return NextResponse.json({error:'Transaksi kas tidak ditemukan.'},{status:404});if(existing.paymentId||existing.expenseId)return NextResponse.json({error:'Transaksi otomatis tidak dapat dihapus manual.'},{status:409});await prisma.cashflowTransaction.delete({where:{id}});await writeAuditLog({workspaceId:c.workspace.id,actorUserId:c.user.id,action:'DELETE',entityType:'CASHFLOW_TRANSACTION',entityId:id,metadata:{}});return NextResponse.json({ok:true})}
